# ATTENTION! THIS ISN'T A FULLY FUNCTIONAL EXAMPLE.
# You should take portions of this example and edit the options to make
# them suitable for your use.
# This file is useful to know all the available options.
kibot:
  version: 1

globals:
  resources_dir: resources
  field_lcsc_part: "LCSC Part"
  solder_mask_color: black
  pcb_finish: ENIG

filters:
  - name: only_jlc_parts
    comment: "Only parts with JLC (LCSC Part) code"
    type: generic
    include_only:
      - column: "LCSC Part"
        regex: '^C\d+'

variants:
  - name: rotated
    comment: "Rotate for JLCPCB"
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint_jlcpcb

outputs:
  - name: "Step"
    comment: "Exports the PCB as a 3D model."
    type: "step"
    dir: "Step"
    options:
      download: false
      download_lcsc: False
      metric_units: true
  - name: "report"
    comment: "Generates a report about the design."
    type: "report"
    dir: "report"
    options:
      converted_output: "%f-%i%I%v.%x"
      eurocircuits_class_target: "3B"
      eurocircuits_reduce_holes: 0
      template: "full"
      do_convert: true
      convert_to: "pdf"
  - name: "pdf_sch_print_dark"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      background_color: true
      color_theme: "Arcana"
      monochrome: false
      dnf_filter: ""
      output: "%f-%i%I%v-dark.%x"
      title: "AstraDriver - Schematic"
  - name: "pdf_sch_print_default"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      monochrome: false
      output: "%f-%i%I%v-default.%x"
      title: "AstraDriver - Schematic"
  - name: "pdf_sch_print_mono"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      monochrome: true
      output: "%f-%i%I%v-mono.%x"
      title: "AstraDriver - Schematic"

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: JLCPCB/Gerber
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - In1.Cu
      - In2.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: JLCPCB/Drill
    options:
      pth_and_npth_single_file: false
      pth_id: "-PTH"
      npth_id: "-NPTH"
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

  - name: ibom
    comment: Interactive BOM
    type: ibom
    dir: IBOM
    options:
      dark_mode: true
      name_format: "index"
      include_tracks: true
      show_fields: "Value,Footprint,Datasheet,LCSC"

  - name: "JLCPCB_position"
    comment: "Pick and place file, JLCPCB style"
    type: position
    dir: JLCPCB/PickAndPlace
    options:
      variant: rotated
      output: "%f_cpl_jlc.%x"
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: false
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: "JLCPCB_bom"
    comment: "BoM for JLCPCB"
    type: bom
    dir: JLCPCB/BOM
    options:
      output: "%f_%i_jlc.%x"
      exclude_filter: "only_jlc_parts"
      ref_separator: ","
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: "LCSC Part"
          name: "LCSC Part #"
        - field: "Quantity Per PCB"
          name: "QTY"
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true
  - name: "Eurocircuits_bom"
    comment: "BoM for Eurocircuits"
    type: bom
    dir: Eurocircuits/BOM
    options:
      output: "%f_%i_jlc.%x"
      exclude_filter: "only_jlc_parts"
      ref_separator: ","
      columns:
        - field: MPN
          name: Manufacturer Part Number
        - field: Description
          name: Description
        - field: References
          name: Reference Designator
        - field: Quantity Per PCB
          name: Quantity
        - field: Value
          name: Value
        - field: Extra Values
          name: Comment
        - field: Footprint
          name: Package name
        - field: MFN
          name: Manufacturer
        - field: Datasheet
          name: URL
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true
  - name: 'Kiri Dark'
    comment: 'Generates a dark version of an interactive web page to browse the schematic and/or PCB differences between git commits.'
    type: 'kiri'
    dir: 'KiRiDark'
    options:
      color_theme: "Arcana"
      background_color: '#000000'
      keep_generated: false
      max_commits: 3
      revision: 'HEAD'
      zones: 'global'
    layers: all
  - name: 'Kiri Light'
    comment: 'Generates a light version of an interactive web page to browse the schematic and/or PCB differences between git commits.'
    type: 'kiri'
    dir: 'KiRiLight'
    options:
      keep_generated: false
      max_commits: 3
      revision: 'HEAD'
      zones: 'global'
    layers: all
  - name: "Markdown components table"
    comment: "All LCSC components in HTML"
    type: bom
    dir: BOM
    options:
      output: "%f_%i.%x"
      exclude_filter: "only_jlc_parts"
      columns:
        - field: Value
          name: Value
        - field: References
          name: Reference
        - field: "Extra Values"
          name: "Extra Values"
        - Footprint
        - field: MFN
          name: "Manufacturer"
        - field: MPN
          name: "Manufacturer Part Number"
        - Datasheet
        - Sheetpath
        - field: "LCSC Part"
          name: "LCSC Part #"
        - field: "Quantity Per PCB"
          name: "Quantity"
      format: "HTML"
      html:
        datasheet_as_link: "Datasheet"
        lcsc_link: true

  - name: "Info"
    comment: "Records information about the current run."
    type: "info"
    dir: "CI"
    options:
      environment: "names"
      output: "%f-%i%I%v.%x"
